[project]
name = "nba-pub-sub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "google-cloud-pubsub>=2.29.1",
    "uvicorn>=0.34.3",
]
